access_log /var/log/nginx/host_access.log combined;
error_log /var/log/nginx/host_error.log warn;


#rewrite ^(.*)/192k\.mp3$ $1/128k.aac redirect;

# Add custom configuration for AzuraVote
location ^~ /votes/ {
    proxy_pass http://172.17.0.1:3099/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}


# Add endpoint for an external stream to push song info to the Azuracast player widget
location = /loopsradio-metadata {
    proxy_pass https://progressive.ozelip.com:7670/currentsong?sid=1;

    proxy_ssl_server_name on;
    proxy_ssl_name progressive.ozelip.com;

    proxy_set_header Host progressive.ozelip.com;
    proxy_set_header Accept text/plain;
    proxy_set_header User-Agent "Mozilla/5.0";

    proxy_connect_timeout 5s;
    proxy_read_timeout 5s;
    proxy_send_timeout 5s;

    proxy_hide_header Access-Control-Allow-Origin;

    add_header Access-Control-Allow-Origin "$http_origin" always;
    add_header Vary "Origin" always;
    add_header Cache-Control "no-store" always;
}

# More endpoints?
#location = /yogachill-metadata {
#    proxy_pass https://radio4.vip-radios.fm:18027/stream-128kmp3-YogaChill;
#
#    proxy_ssl_server_name on;
#    proxy_ssl_name radio4.vip-radios.fm;
#
#    proxy_set_header Host radio4.vip-radios.fm;
#    proxy_set_header Accept text/plain;
#    proxy_set_header User-Agent "Mozilla/5.0";
#
#    proxy_connect_timeout 5s;
#    proxy_read_timeout 5s;
#    proxy_send_timeout 5s;
#
